action: log vars

diff --git a/.github/workflows/master_hoster.yml b/.github/workflows/master_hoster.yml
--- a/.github/workflows/master_hoster.yml
+++ b/.github/workflows/master_hoster.yml
@@ -128,6 +128,8 @@ jobs:
           if [ -z "$STORAGE_KEY" ]; then
             echo "Error: STORAGE_KEY is empty or not found."
             exit 1
+          else
+            echo "STORAGE_KEY: $STORAGE_KEY"
           fi
           echo "AZURE_STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT}" >> $GITHUB_OUTPUT
           echo "AZURE_STORAGE_ACCOUNT_KEY=${STORAGE_KEY}" >> $GITHUB_OUTPUT
@@ -218,7 +220,19 @@ jobs:
       - name: Set environment variables
         run: |
           echo "AZURE_STORAGE_ACCOUNT_NAME=${{ needs.build-backend.outputs.AZURE_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
+          if [ -z "$AZURE_STORAGE_ACCOUNT_NAME" ]; then
+            echo "Error: AZURE_STORAGE_ACCOUNT_NAME is empty or not found."
+            exit 1
+          else
+            echo "AZURE_STORAGE_ACCOUNT_NAME: $AZURE_STORAGE_ACCOUNT_NAME"
+          fi
           echo "AZURE_STORAGE_ACCOUNT_KEY=${{ needs.build-backend.outputs.AZURE_STORAGE_ACCOUNT_KEY }}" >> $GITHUB_ENV
+          if [ -z "$AZURE_STORAGE_ACCOUNT_KEY" ]; then
+            echo "Error: AZURE_STORAGE_ACCOUNT_KEY is empty or not found."
+            exit 1
+          else
+            echo "AZURE_STORAGE_ACCOUNT_KEY: $AZURE_STORAGE_ACCOUNT_KEY"
+          fi 
 
       - name: Download backend artifact
         uses: actions/download-artifact@v4
