action: check null storage values

diff --git a/.github/workflows/master_hoster.yml b/.github/workflows/master_hoster.yml
--- a/.github/workflows/master_hoster.yml
+++ b/.github/workflows/master_hoster.yml
@@ -121,8 +121,15 @@ jobs:
         id: setvars
         run: |
           STORAGE_ACCOUNT=$(az storage account list --query '[0].name' -o tsv)
+          if [ -z "$STORAGE_ACCOUNT" ]; then
+            echo "Error: STORAGE_ACCOUNT is empty or not found."
+            exit 1
+          fi
           STORAGE_KEY=$(az storage account keys list --account-name ${STORAGE_ACCOUNT} --resource-group 'hoster' --query '[0].value' -o tsv)
-          
+          if [ -z "$STORAGE_KEY" ]; then
+            echo "Error: STORAGE_KEY is empty or not found."
+            exit 1
+          fi
           echo "AZURE_STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT}" >> $GITHUB_OUTPUT
           echo "AZURE_STORAGE_ACCOUNT_KEY=${STORAGE_KEY}" >> $GITHUB_OUTPUT
           echo "BACKEND_URL=$BACKEND_URL" >> $GITHUB_OUTPUT
