comment out set vars

diff --git a/.github/workflows/master_hoster.yml b/.github/workflows/master_hoster.yml
--- a/.github/workflows/master_hoster.yml
+++ b/.github/workflows/master_hoster.yml
@@ -217,24 +217,24 @@ jobs:
       url: ${{ steps.deploy-backend.outputs.webapp-url }}
     
     steps:
-      - name: Set environment variables
-        run: |
-          export "AZURE_STORAGE_ACCOUNT_NAME=${{ needs.build-backend.outputs.AZURE_STORAGE_ACCOUNT_NAME }}" 
-          echo "AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_ACCOUNT_NAME" >> $GITHUB_ENV
-          if [ -z "$AZURE_STORAGE_ACCOUNT_NAME" ]; then
-            echo "Error: AZURE_STORAGE_ACCOUNT_NAME is empty or not found."
-            exit 1
-          else
-            echo "AZURE_STORAGE_ACCOUNT_NAME: $AZURE_STORAGE_ACCOUNT_NAME"
-          fi
-          export "AZURE_STORAGE_ACCOUNT_KEY=${{ needs.build-backend.outputs.AZURE_STORAGE_ACCOUNT_KEY }}"
-          echo "AZURE_STORAGE_ACCOUNT_KEY=$AZURE_STORAGE_ACCOUNT_KEY" >> $GITHUB_ENV
-          if [ -z "$AZURE_STORAGE_ACCOUNT_KEY" ]; then
-            echo "Error: AZURE_STORAGE_ACCOUNT_KEY is empty or not found."
-            exit 1
-          else
-            echo "AZURE_STORAGE_ACCOUNT_KEY: $AZURE_STORAGE_ACCOUNT_KEY"
-          fi
+      # - name: Set environment variables
+      #   run: |
+      #     export "AZURE_STORAGE_ACCOUNT_NAME=${{ needs.build-backend.outputs.AZURE_STORAGE_ACCOUNT_NAME }}" 
+      #     echo "AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_ACCOUNT_NAME" >> $GITHUB_ENV
+      #     if [ -z "$AZURE_STORAGE_ACCOUNT_NAME" ]; then
+      #       echo "Error: AZURE_STORAGE_ACCOUNT_NAME is empty or not found."
+      #       exit 1
+      #     else
+      #       echo "AZURE_STORAGE_ACCOUNT_NAME: $AZURE_STORAGE_ACCOUNT_NAME"
+      #     fi
+      #     export "AZURE_STORAGE_ACCOUNT_KEY=${{ needs.build-backend.outputs.AZURE_STORAGE_ACCOUNT_KEY }}"
+      #     echo "AZURE_STORAGE_ACCOUNT_KEY=$AZURE_STORAGE_ACCOUNT_KEY" >> $GITHUB_ENV
+      #     if [ -z "$AZURE_STORAGE_ACCOUNT_KEY" ]; then
+      #       echo "Error: AZURE_STORAGE_ACCOUNT_KEY is empty or not found."
+      #       exit 1
+      #     else
+      #       echo "AZURE_STORAGE_ACCOUNT_KEY: $AZURE_STORAGE_ACCOUNT_KEY"
+      #     fi
 
       - name: Output shared variables
         id: setvars
